import type { ProductForm, ProductType, ProjectForm } from "@/types";

export const productTypes: ProductType[] = [
  "ELECTRONICS_COMPONENT",
  "MODULE",
  "SENSOR",
  "DEVELOPMENT_BOARD",
  "MOTOR_ACTUATOR",
  "POWER_BATTERY",
  "TOOL_EQUIPMENT",
  "COURSE_KIT",
  "BOOK",
  "SOFTWARE",
  "CUSTOM_PROJECT_SERVICE",
  "OTHER",
];

export const projectCategories = [
  "IOT",
  "ROBOTICS",
  "DRONE",
  "AUTOMATION",
  "ENVIRONMENT",
  "HEALTH",
  "AGRICULTURE",
  "SECURITY",
  "EDUCATION",
  "AUTOMOTIVE",
  "SMART_HOME",
  "ENERGY",
  "WEARABLES",
  "GAMING",
  "COMMUNICATION",
  "AI_ML",
  "COMPUTER_VISION",
  "OTHER",
];

export const orderStatuses = [
  "PENDING_PAYMENT",
  "PAID",
  "PROCESSING",
  "PACKED",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "RETURN_REQUESTED",
  "RETURNED",
  "REFUND_INITIATED",
  "REFUNDED",
  "CANCELLED",
] as const;

export const emptyProductForm: ProductForm = {
  id: "",
  name: "",
  slug: "",
  sku: "",
  description: "",
  typicalUseCase: "",
  vendorLink: "",
  imageUrl: "",
  category: "Electronics Components",
  subcategory: "General",
  productType: "ELECTRONICS_COMPONENT",
  brand: "",
  tags: "",
  unitPrice: "",
  discountedPrice: "",
  stockQuantity: "0",
  isBestSeller: false,
  isRobomaniacItem: false,
  isSoftware: false,
  isActive: true,
};

export const emptyProjectForm: ProjectForm = {
  id: "",
  title: "",
  summary: "",
  description: "",
  category: "ROBOTICS",
  difficulty: "BEGINNER",
  youtubeUrl: "",
  thumbnailUrl: "",
  estimatedCost: "",
  estimatedBuildTimeMinutes: "",
  tags: "",
  learningOutcomes: "",
  prerequisites: "",
  preBuiltAvailable: false,
  preBuiltPrice: "",
  preBuiltStock: "",
  imageUrls: "",
  pdfUrls: "",
  isFeatured: false,
  isPublic: true,
};
